name: Unit Test & Upload Coverage XML

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master ]

jobs:
  generate-code-coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: ${{ !env.ACT }}
        uses: actions/checkout@v4

      - name: Set node version
        uses: actions/setup-node@v4
        with:
            node-version: 20.11.1
            cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage report
        run: npm run test:cov

      - name: Upload code coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/jest/cobertura-coverage.xml

